### ISSUE TITLE
Focus styling in Firefox

### ISSUE THREAD

**Issue by brendanfalkowski** [filamentgroup/select-css#35]
Hi @scottjehl — Super excited your team is still working on making this better. I refactored a project using my custom styles based on the old version and got the pixel-for-pixel same outcome.

I noticed one line on Firefox focus ring styles that uses a property I couldn't find any docs for: `-moz-mac-focusring`. Not sure I've ever seen a vendor-specific value before.

```css
.select-css:focus {
	border-color: #aaa;
	/* It'd be nice to use -webkit-focus-ring-color here but it doesn't work on box-shadow */
	box-shadow: 0 0 1px 3px rgba(59, 153, 252, .7);
	box-shadow: 0 0 0 3px -moz-mac-focusring;
	color: #222; 
	outline: none;
}
```

The `:-moz-focusring` pseduo-class seems to be the standard: https://developer.mozilla.org/en-US/docs/Web/CSS/:-moz-focusring

Firefox still renders the dotted focus ring after making a selection:

![screen shot 2018-12-20 at 12 14 59 pm](https://user-images.githubusercontent.com/214924/50308711-f670e780-0450-11e9-9503-289765b4036a.png)

I wasn't sure if it was intentional for the repo to keep this, but there is alternative focus styling for accessiblity.

I removed the `-moz-mac-focusring` code, and tested a technique to hide disable the dotted line (Firefox is so weird) which feels gross but works:

![screen shot 2018-12-20 at 12 17 34 pm](https://user-images.githubusercontent.com/214924/50308879-76974d00-0451-11e9-9a77-8e13f4211517.png)

Are you open to PRs that modify this?

I'd also like to see styling for `:disabled` included so it's covered minimally. I like doing `opacity: 0.5`
